version: '3.4'
services:
  mongo:
    container_name: mongo-svc
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021
      MONGO_INITDB_DATABASE: compassolisa
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo:/var/lib/mongo
    networks:
      - mongo-compose-network
  
  mongo-express:
    container_name: express-svc
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2021
      ME_CONFIG_MONGODB_URL: "mongodb://root:MongoDB2021@mongo-svc:27017/"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
  app:
    container_name: api-svc
    build: .
    ports:
        - "3000:3000"
    environment:
      MONGO_HOST: mongo-svc:27017
      MONGO_USER: root
      MONGO_PASSWORD: MongoDB2021
      MONGO_COLLECTION: compassolisa
      NODE_ENV: prod
      PORT: 3000
    entrypoint:
      - npm
      - run
      - start
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
networks:
    mongo-compose-network:
      driver: bridge